### ISSUE TITLE
Encoder data in simulation

### ISSUE THREAD

**Issue by Aleksej9521** [fjp/2wd-robot#65]
Hi, great work. I have a question: is there an implementation of the encoder data also on the simulation? Because I can't find it.

**Comment by fjp** [comment]
Hi thank you @AlessiaLiNoce for the kind feedback. 

The simulation of diffbot relies on the [gazebo ros control plugin](https://classic.gazebosim.org/tutorials?tut=ros_control&cat=connect_ros) and as far as I know there is no encoder data available (please see also the [src](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/noetic-devel/gazebo_ros_control/include/gazebo_ros_control)).

You might be able to convert the joint angle velocities back to encoder ticks if you really need it in simulation.

Alternatively [ros_diff_drive gazebo plugin](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/231a7219b36b8a6cdd100b59f66a3df2955df787/gazebo_plugins/src/gazebo_ros_diff_drive.cpp) might provide what you need but this is not used by diffbot.
